#!/usr/bin/env node
/**
 * Turns FIREBASE_* variables into a typed, git-ignored module for the shell:
 * apps/shell/src/environments/firebase-config.generated.ts
 *
 * Sources, in order: variables already in the environment (CI secrets, or the
 * root .env that Nx loads for every task), then the root .env when this script
 * runs outside Nx (e.g. postinstall).
 *
 * All-or-nothing: if any required value is missing, the module exports `null`
 * and the app runs without Firebase. A half-configured SDK fails in confusing
 * ways at runtime, so this avoids that.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../..');
const OUT = resolve(
	ROOT,
	'apps/shell/src/environments/firebase-config.generated.ts',
);

const envFile = resolve(ROOT, '.env');
if (existsSync(envFile)) {
	// Does not override variables that are already set (e.g. CI secrets).
	process.loadEnvFile(envFile);
}

const REQUIRED = {
	apiKey: 'FIREBASE_API_KEY',
	authDomain: 'FIREBASE_AUTH_DOMAIN',
	projectId: 'FIREBASE_PROJECT_ID',
	storageBucket: 'FIREBASE_STORAGE_BUCKET',
	messagingSenderId: 'FIREBASE_MESSAGING_SENDER_ID',
	appId: 'FIREBASE_APP_ID',
};
const OPTIONAL = { measurementId: 'FIREBASE_MEASUREMENT_ID' };

const read = (name) => process.env[name]?.trim() ?? '';
const missing = Object.values(REQUIRED).filter((name) => !read(name));

let config = null;
if (missing.length === 0) {
	config = Object.fromEntries(
		Object.entries({ ...REQUIRED, ...OPTIONAL })
			.map(([key, name]) => [key, read(name)])
			.filter(([, value]) => value),
	);
} else if (missing.length < Object.keys(REQUIRED).length) {
	console.warn(
		`[generate-env] Firebase disabled: missing ${missing.join(', ')} in .env`,
	);
}

const source = `// AUTO-GENERATED by tools/scripts/generate-env.mjs from .env. Do not edit or commit.
import type { FirebaseWebConfig } from './firebase-config';

export const firebaseConfig: FirebaseWebConfig | null = ${JSON.stringify(config, null, '\t')};
`;

// Only write on change, so file watchers do not rebuild for nothing.
const previous = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
if (previous !== source) writeFileSync(OUT, source);
console.log(
	`[generate-env] Firebase ${config ? `configured (${config.projectId})` : 'not configured'}`,
);
